### ISSUE TITLE
BUG: Expired GPG key causes downstream failures

### ISSUE THREAD

**Issue by wbenoit26** [cicirello/pyaction#235]
**Describe the bug**
Due to GitHub CLI's GPG expiring (see [cli/cli#9569](https://github.com/cli/cli/issues/9569)), downstream layers in the docker build that run `apt-get update` are failing. I believe all that's needed to fix this is a re-build of the container.

**To Reproduce**
1. First, run `docker run cicirello/pyaction:latest apt-get update`
2. This should produce the following error:
```
Get:1 http://deb.debian.org/debian bookworm InRelease [151 kB]
Get:2 http://deb.debian.org/debian bookworm-updates InRelease [55.4 kB]
Get:3 http://deb.debian.org/debian-security bookworm-security InRelease [48.0 kB]
Get:4 https://cli.github.com/packages stable InRelease [3917 B]
Get:5 http://deb.debian.org/debian bookworm/main amd64 Packages [8787 kB]
Err:4 https://cli.github.com/packages stable InRelease
  The following signatures were invalid: EXPKEYSIG 23F3D4EA75716059 GitHub CLI <opensource+cli@github.com>
Get:6 http://deb.debian.org/debian bookworm-updates/main amd64 Packages [2468 B]
Get:7 http://deb.debian.org/debian-security bookworm-security/main amd64 Packages [182 kB]
Reading package lists...
W: GPG error: https://cli.github.com/packages stable InRelease: The following signatures were invalid: EXPKEYSIG 23F3D4EA75716059 GitHub CLI <opensource+cli@github.com>
E: The repository 'https://cli.github.com/packages stable InRelease' is not signed.
```

**Expected behavior**
`apt-get update` should be able to be run within the container

**Relevant System Info (please complete the following information):**
 - Ubuntu
 - 24.04

**Comment by cicirello** [comment]
@wbenoit26 thanks for reporting. I'll try to take a look tomorrow. From looking at the issue you linked to, I think you are right that rebuilding should fix it

**Comment by cicirello** [comment]
@wbenoit26 this is now fixed. Thanks again for reporting.

**Comment by wbenoit26** [comment]
Great, thanks for fixing this so quickly!

**Comment by wbenoit26** [comment]
@cicirello Would you also be able to re-build some earlier versions of this container? My project doesn't yet support Python 3.12

**Comment by leaffan** [comment]
Same here as well. Any chance to re-build the most recent version supporting Python 3.11? It would be greatly appreciated.

**Comment by cicirello** [comment]
@leaffan I'll try to take a look at it tomorrow.
